// Mocks generated by Mockito 5.4.4 from annotations
// in xingcam/test/features/retro_camera/domain/usecases/get_filter_presets_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xingcam/core/error/failures.dart' as _i5;
import 'package:xingcam/features/retro_camera/domain/entities/captured_photo.dart'
    as _i7;
import 'package:xingcam/features/retro_camera/domain/entities/filter_preset.dart'
    as _i6;
import 'package:xingcam/features/retro_camera/domain/repositories/retro_camera_repository.dart'
    as _i3;
import 'package:xingcam/features/retro_camera/presentation/widgets/film_border_overlay.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RetroCameraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetroCameraRepository extends _i1.Mock
    implements _i3.RetroCameraRepository {
  MockRetroCameraRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FilterPreset>>>
      getFilterPresets() => (super.noSuchMethod(
            Invocation.method(
              #getFilterPresets,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.FilterPreset>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.FilterPreset>>(
              this,
              Invocation.method(
                #getFilterPresets,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.FilterPreset>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CapturedPhoto>> capturePhoto({
    required String? rawImagePath,
    required _i6.FilterPreset? selectedPreset,
    required double? grainIntensity,
    required String? lightLeakAsset,
    required _i8.FilmBorderType? borderType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #capturePhoto,
          [],
          {
            #rawImagePath: rawImagePath,
            #selectedPreset: selectedPreset,
            #grainIntensity: grainIntensity,
            #lightLeakAsset: lightLeakAsset,
            #borderType: borderType,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.CapturedPhoto>>.value(
                _FakeEither_0<_i5.Failure, _i7.CapturedPhoto>(
          this,
          Invocation.method(
            #capturePhoto,
            [],
            {
              #rawImagePath: rawImagePath,
              #selectedPreset: selectedPreset,
              #grainIntensity: grainIntensity,
              #lightLeakAsset: lightLeakAsset,
              #borderType: borderType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.CapturedPhoto>>);
}
