// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sovereign Native Image Resizer.
/// Pushes array memory into static C-level blocks, preventing arbitrary OOM conditions
/// prevalent in standard Dart Canvas implementations.
Future<String> safeDownsampleForAi(
        {required String inputPath,
        required String outputPath,
        required int targetSize}) =>
    RustLib.instance.api.crateApiSafeDownsampleForAi(
        inputPath: inputPath, outputPath: outputPath, targetSize: targetSize);

/// Compute C2PA signatures mathematically bypassing Dart array clones
Future<String> computeC2PaHmac({required String filePath}) =>
    RustLib.instance.api.crateApiComputeC2PaHmac(filePath: filePath);

/// Vectorized 3D LUT Parser (.cube to RGBA).
/// High-performance string parsing bypassing the heavy Dart String split overhead.
Future<Uint8List> parse3DLut({required String content}) =>
    RustLib.instance.api.crateApiParse3DLut(content: content);

/// Sovereign Patch-Match Lite (v2.0 Professional) - Native Implementation
/// Moves the 96 million operations off the Dart VM and onto the LLVM-optimized Rust backend
/// for zero-lag native offline inpainting.
Future<String> localInpaint(
        {required String imagePath,
        required String maskPath,
        required String outputPath}) =>
    RustLib.instance.api.crateApiLocalInpaint(
        imagePath: imagePath, maskPath: maskPath, outputPath: outputPath);
